22 feature about us mission section
nology-tech/positive-pup pull request #19
Opened 2022-03-28 14:53 UTC by j-jinjia

1. My mission section: added the content and stylings
2. Responsiveness on mobile devices and desktop
3. Added predetermined typography for h1,h2 and h3 headers.

2022-03-28 14:59 UTC, DanForder requested changes

2022-03-28 14:59 UTC, DanForder commented on src/components/MissionSection/MissionSection.scss
> +    );
Do we need all these colours and percentages specified? (not a leading question, just curious why they add up to 200% rather than 100%)

2022-03-28 14:59 UTC, DanForder commented on src/components/MissionSection/MissionSection.jsx
> +        <br />
instead of using `<br/>`, use multiple `<p>` tags. Each one is a separate paragraph!

2022-03-28 15:18 UTC, j-jinjia commented on src/components/MissionSection/MissionSection.scss
> +      grid-column-start: 2;
I think we need it because we set the whole section to display:grid, so we need the link to start at a specific column.

2022-03-28 15:23 UTC, j-jinjia commented on src/components/MissionSection/MissionSection.scss
> +    );
We needed the percentages so it can display the background. we took the code from the internet.
But we deleted 1 transparent percentage.

2022-03-28 15:30 UTC, DanForder commented on src/components/MissionSection/MissionSection.scss
> +    );
could the same thing be achieved with `linear-gradient(to right, transparent 15%, $colour-primary-light 85%);` ?

2022-03-28 15:33 UTC, j-jinjia commented on src/components/MissionSection/MissionSection.scss
> +    );
No, with that it starts faded white and then slowly turns into our colour blue. If we keep it as it is, it will display a blue box as a background

2022-03-29 07:52 UTC, DanForder requested changes

2022-03-29 07:52 UTC, DanForder commented on src/components/MissionSection/MissionSection.jsx
> +        </a>{" "}
Do you need the whitespaces? (`{" "}`)

2022-03-29 07:52 UTC, DanForder commented on src/components/MissionSection/MissionSection.jsx
> +        <img className="link-container__arrow" src={arrow} />
add alt tag (it can be an empty string if just an icon)

2022-03-29 07:52 UTC, DanForder commented on src/components/MissionSection/MissionSection.test.js
> +it("should render the footer component", () => {
*MissionSection component

2022-03-29 13:05 UTC, DanForder approved these changes

2022-03-29 13:05 UTC, merged