35 landing page services functionality only
nology-tech/positive-pup pull request #25
Opened 2022-03-29 15:08 UTC by Andy-Reynolds

2022-03-30 11:21 UTC, DanForder requested changes
fix PR build issues

2022-03-30 13:43 UTC, DanForder commented on src/components/ServicesCard/ServicesCard.jsx
> +      <h1 className="services-card__title">{title}</h1>
There should only ever be one H1 on each page.

Think about the hierarchy of your headings on this page. Each heading should make sense semantically underneath it's parent. 

For example:

h1 : Services
h2: Services I offer
h3: Online Courses, h3: Bespoke Courses, h3 Group Courses

2022-03-30 13:43 UTC, DanForder commented on src/components/ServicesCard/ServicesCard.jsx
> +      <h2>{description}</h2>
The description is probably best as `<p>` tag

2022-03-30 13:43 UTC, DanForder commented on src/components/ServicesCard/ServicesCard.jsx
> +          {/* Put a second chevron here of a different colour with display=none. We can use this to change the colour when we add hover later */}
remove comment

2022-03-30 13:44 UTC, DanForder commented on src/components/ServicesCard/ServicesCard.jsx
> +        <div className="services-card__button">
can you remove this div and put the className on the `Link` component? could remove a bit of unnecessary html

2022-03-30 13:44 UTC, DanForder commented on src/components/ServicesCard/ServicesCard.scss
> +  //when all content is in, this can be changed to max height
remove comment/ max-height is probably better too

2022-03-30 13:46 UTC, DanForder commented on src/components/ServicesCard/ServicesCard.scss
> +      display: none;
if this is always hidden do we need it at all in the html?

2022-03-30 13:47 UTC, DanForder commented on src/components/ServicesSection/ServicesSection.jsx
> +        className="services-section__button"
does Button have a prop called className that you're using?

2022-03-30 13:48 UTC, DanForder commented on src/components/ServicesSection/ServicesSection.scss
> +  .button--secondary {
we shouldn't be modifying the button component like this from outside the button styles. You could create a clasname prop on button if required

2022-03-30 13:49 UTC, DanForder commented on src/components/ServicesSection/ServicesSection.jsx
> +const ServicesSection = ({ link }) => {
does link need to be a prop? don't think this is going to change so might be okay to be hard coded on line 34

2022-03-30 15:41 UTC, Andy-Reynolds commented on src/components/ServicesCard/ServicesCard.jsx
> +          {/* Put a second chevron here of a different colour with display=none. We can use this to change the colour when we add hover later */}
Can we leave this comment for now as a reference for the next person to pick up the ticket?

2022-03-31 16:16 UTC, closed without merging

2022-03-31 16:16 UTC, Andy-Reynolds commented
Duplicate Branch - closed request