43 feature services category filter
nology-tech/positive-pup pull request #51
Opened 2022-04-06 15:56 UTC by singapaul

Integrated both category and text search filters for the services page

2022-04-06 16:09 UTC, DanForder requested changes

2022-04-07 13:40 UTC, singapaul commented on src/components/CategoryFilter/CategoryFilter.scss
> +.category-filter-container {
resolved

2022-04-07 13:45 UTC, singapaul commented on src/pages/Services/Services.jsx
> +  ];
done

2022-04-07 13:52 UTC, singapaul commented on src/pages/Services/Services.jsx
> +  ];
done

2022-04-07 14:41 UTC, merged