25 feature course card
nology-tech/positive-pup pull request #9
Opened 2022-03-22 16:55 UTC by j-jinjia

1. Created course card component
2. Rendered it using props in services component(page)
3. Styled the card 
4. Added a few variables in the scss variables file.

2022-03-23 14:19 UTC, DanForder requested changes

2022-03-23 14:19 UTC, DanForder commented on src/components/CourseCard/CourseCard.jsx
> +          <span className="course-content__labels">{filterLabels[1]}</span>
What if we only have one array item? What if we have 4? Let's allow this component to handle these other scenarios

2022-03-23 14:19 UTC, DanForder commented on src/components/CourseCard/CourseCard.jsx
> +          <span className="course-content__labels">{filterLabels[0]}</span>
`course-content__labels` should be the singular: `course-content__label`

2022-03-23 14:19 UTC, DanForder commented on src/styles/_variables.scss
> +$colour-primary-dark-grey: #525252;
Give these names that have some meaning, if we wanted to change the theme, we might not want teal and grey anymore!

2022-03-23 14:19 UTC, DanForder commented on src/components/CourseCard/CourseCard.scss
> +            font-family: $font-general;
let's set the default font in the typography file, this way we don't need to specify it inside each component

2022-03-23 15:35 UTC, j-jinjia commented on src/components/CourseCard/CourseCard.scss
> +            font-family: $font-general;
Do you mean setting the font family in the typography.scss file for the course card? or just don't add a font family ?

2022-03-23 15:50 UTC, DanForder requested changes

2022-03-23 15:50 UTC, DanForder commented on src/components/CardLabel/CardLabel.jsx
> +    <div className="label">
classname should match component name: `card-label`

2022-03-23 15:50 UTC, DanForder commented on src/components/CourseCard/CourseCard.jsx
> +      <div className="course-content">
classname should be consistent, everything should start with `course-card` not `course-content`

2022-03-23 15:50 UTC, DanForder commented on src/components/CourseCard/CourseCard.scss
> +        padding:0.5rem; */
remove commented code

2022-03-23 15:50 UTC, DanForder commented on src/styles/_typography.scss
> +  font-family: $font-general;
Make sure to have a fallback font here, so `$font-general, sans-serif;` in case the font-general doesn't load

2022-03-23 15:50 UTC, DanForder commented on src/styles/_variables.scss
>  $colour-footer-primary: #525252;
let's merge these two color variables into a single one!

2022-03-24 14:15 UTC, DanForder requested changes

2022-03-24 14:15 UTC, DanForder commented on src/styles/_typography.scss
>  }
did you mean to delete the font-size: 1rem; ?

2022-03-24 14:22 UTC, DanForder approved these changes

2022-03-24 14:22 UTC, merged